### ISSUE TITLE
Error on function "run()"

### ISSUE THREAD

**Issue by s-manning** [Hiroyu/_PyVox#4]
Hi, 

I'm running Windows and I always get this error: **_TypeError: run() takes 1 positional argument but 3 were given_**
It doesn't matter how many arguments I give, this error always shows up. Any Idea why?

**Comment by Veykril** [comment]
Did you update your installation of discord.py to the latest one? And how are you starting the bot?

**Comment by s-manning** [comment]
Ok, after I updated the discord.py it partially works. The bot runs perfectly if I comment out the following:
**_if not discord.opus.is_loaded():
    discord.opus.load_opus('libopus-0')_**

But opus is needed to play the sounds I guess. So I have the _opus.dll_ and the _libopus-0.dll_ in the same directory as the script, but then I get this error:
***
Traceback (most recent call last):
  File "D:\location_PyVox-master (1)_PyVox-master\pyvox.py", line 14, in <module>
    discord.opus.load_opus('libopus-0')
  File "C:\Users\user\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\opus.py", line 113, in load_opus
    _lib = libopus_loader(name)
  File "C:\Users\user\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\opus.py", line 57, in libopus_loader
    lib = ctypes.cdll.LoadLibrary(name)
  File "C:\Users\user\AppData\Local\Programs\Python\Python35\lib\ctypes__init**.py", line 425, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\user\AppData\Local\Programs\Python\Python35\lib\ctypes__init__.py", line 347, in **init**
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 ist keine zulässige Win32-Anwendung
*__

**Comment by Veykril** [comment]
Do you have installed a 64bit version of python? If yes try using a 32 bit version

**Comment by s-manning** [comment]
Okay, that sloved the Problem, thanks.
